server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    database: ${sky.redis.database}
    host: ${sky.redis.host}
    port: ${sky.redis.port}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-token-name: authentication

    user-ttl: 7200000

    user-secret-key: ${sky.jwt.key}


  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mchid: ${sky.dev.wechat.mchid}
    mchSerialNo: ${sky.dev.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.dev.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiVersion3Key}
    weChatPayCertFilePath: ${sky.dev.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.dev.wechat.notifyUr1}
    refundNotifyUrl: ${sky.dev.wechat.refundNotifyUr1}

  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

